"use client";
import{useEffect,useMemo,useRef,useState}from"react";
import{gameAudio}from"@/lib/audio/gameAudio";
import type{MiniGameProps}from"../types";
import{DUEL_ITEMS}from"./data";
import{applyDuelItem,chooseDealerAction,countShells,createDuel,fireChamber,seeded}from"./rules";
import type{DuelActor,DuelResult,DuelState}from"./types";
import styles from"./FateChamber.module.css";
const IDLE:DuelState={phase:"idle",turn:"player",round:0,chamber:[],playerHp:5,dealerHp:5,maxHp:5,playerItems:[],dealerItems:[],known:{player:null,dealer:null},shields:{player:false,dealer:false},boosts:{player:false,dealer:false},skip:{player:false,dealer:false},actions:0,score:0,message:"选择目标，判断下一枚能量",history:[]};
export function FateChamber({bestScore,onScore}:MiniGameProps){const[state,setState]=useState<DuelState>(IDLE);const randomRef=useRef(seeded(1));const submitted=useRef(false);const counts=useMemo(()=>countShells(state.chamber),[state.chamber]);
  const start=()=>{randomRef.current=seeded(Date.now());submitted.current=false;const next=createDuel(randomRef.current);setState(next);gameAudio.play("start");};
  const apply=(result:DuelResult)=>{setState(result.state);gameAudio.play(result.event==="charge"?"crash":result.event==="block"?"stack":result.event==="reload"?"flip":"tap");};
  const fire=(target:DuelActor)=>{if(state.phase!=="playing"||state.turn!=="player")return;apply(fireChamber(state,"player",target,randomRef.current));};
  const handleItem=(index:number)=>{if(state.phase!=="playing"||state.turn!=="player")return;apply(applyDuelItem(state,"player",index,randomRef.current));};
  useEffect(()=>{if((state.phase==="won"||state.phase==="lost")&&!submitted.current){submitted.current=true;onScore(state.score);gameAudio.play(state.phase==="won"?"win":"miss");}},[state.phase,state.score,onScore]);
  useEffect(()=>{if(state.phase!=="playing"||state.turn!=="dealer")return;const timer=window.setTimeout(()=>{setState(current=>{if(current.phase!=="playing"||current.turn!=="dealer")return current;const action=chooseDealerAction(current);const result=action.type==="item"?applyDuelItem(current,"dealer",action.index,randomRef.current):fireChamber(current,"dealer",action.target,randomRef.current);gameAudio.play(result.event==="charge"?"crash":result.event==="block"?"stack":result.event==="reload"?"flip":"tap");return result.state;});},720);return()=>window.clearTimeout(timer);},[state]);
  const togglePause=()=>setState(current=>({...current,phase:current.phase==="paused"?"playing":current.phase==="playing"?"paused":current.phase}));
    return <div className={styles.game}>{state.phase!=="idle"&&<><div className={styles.hud}><div className={styles.life}><small>你的生命 {state.shields.player&&"· 护盾"}</small><div className={styles.hearts}>{"♥".repeat(state.playerHp)}{"♡".repeat(state.maxHp-state.playerHp)}</div></div><div className={styles.turn}>第 {state.round} 轮 · {state.turn==="player"?"你的行动":"庄家思考中"}</div><div className={styles.life}><small>{state.shields.dealer&&"护盾 · "}庄家生命</small><div className={styles.hearts}>{"♥".repeat(state.dealerHp)}{"♡".repeat(state.maxHp-state.dealerHp)}</div></div></div><button className={styles.pause} onClick={togglePause}>{state.phase==="paused"?"▶":"Ⅱ"}</button><div className={styles.counts}><span className={`${styles.count} ${styles.countCharge}`}>实能量 <b>{counts.charge}</b></span><span className={`${styles.count} ${styles.countDud}`}>惰性能量 <b>{counts.dud}</b></span></div><div className={styles.message}>{state.message}</div><div className={styles.table}><div className={styles.device}>{Array.from({length:7},(_,index)=><i key={index} className={`${styles.slot} ${index<state.chamber.length?styles.loaded:""}`} style={{"--angle":`${index*360/7}deg`}as React.CSSProperties}/>) }<span className={styles.core}>✦</span></div>{state.known.player&&<div className={styles.known}>观星镜：下一枚是 {state.known.player==="charge"?"实能量":"惰性能量"}</div>}</div><div className={styles.items}>{state.playerItems.map((id,index)=>{const item=DUEL_ITEMS[id];return <button key={`${id}-${index}`} className={styles.item} title={item.description} onClick={()=>handleItem(index)} disabled={state.turn!=="player"||state.phase!=="playing"}><b>{item.icon}</b><span>{item.name}</span></button>;})}</div><div className={styles.actions}><button className={`${styles.fire} ${styles.fireSelf}`} onClick={()=>fire("player")} disabled={state.turn!=="player"||state.phase!=="playing"}>对自己释放</button><button className={styles.fire} onClick={()=>fire("dealer")} disabled={state.turn!=="player"||state.phase!=="playing"}>对庄家释放</button></div><div className={styles.log}>{state.history.map((line,index)=><p key={`${line}-${index}`}>{line}</p>)}</div>{state.turn==="dealer"&&state.phase==="playing"&&<div className={styles.aiThinking}/>}</>}
    {state.phase==="idle"&&<div className={styles.overlay}><span className={styles.sigil}>✦</span><h3>命运弹仓</h3><p>弹仓会公开实能量与惰性能量的数量，但不会公开顺序。使用道具收集情报、改变下一枚能量，再决定把命运交给自己还是庄家。</p><ul><li>惰性能量对自己释放可连续行动</li><li>实能量造成 1 点伤害</li><li>道具每轮重新补充</li></ul><button onClick={start}>签下命运契约</button></div>}
    {(state.phase==="won"||state.phase==="lost")&&<div className={styles.overlay}><span className={styles.sigil}>{state.phase==="won"?"♛":"✦"}</span><h3>{state.phase==="won"?"命运属于你":"契约由庄家收走"}</h3><p>{state.message}。本局 {state.score.toLocaleString()} 分，历史最高 {Math.max(bestScore,state.score).toLocaleString()}。</p><ul><li>进行 {state.round} 轮装填</li><li>执行 {state.actions} 次行动</li></ul><button onClick={start}>再赌一局</button></div>}
    {state.phase==="paused"&&<div className={styles.overlay}><span className={styles.sigil}>Ⅱ</span><h3>契约暂停</h3><p>弹仓和庄家的思考都已冻结。</p><button onClick={togglePause}>继续对局</button></div>}
  </div>;
}
