export const NIGHTFALL_SPRITES = {
  floor: "/assets/kenney-tiny-dungeon/Tiles/tile_0000.png",
  rubble: "/assets/kenney-tiny-dungeon/Tiles/tile_0024.png",
  rune: "/assets/kenney-tiny-dungeon/Tiles/tile_0012.png",
  stone: "/assets/kenney-tiny-dungeon/Tiles/tile_0056.png",
  torch: "/assets/kenney-tiny-dungeon/Tiles/tile_0029.png",
  chest: "/assets/kenney-tiny-dungeon/Tiles/tile_0089.png",
  paladin: "/assets/kenney-tiny-dungeon/Tiles/tile_0097.png",
  ranger: "/assets/kenney-tiny-dungeon/Tiles/tile_0100.png",
  necromancer: "/assets/kenney-tiny-dungeon/Tiles/tile_0084.png",
  mage: "/assets/kenney-tiny-dungeon/Tiles/tile_0099.png",
  elf: "/assets/generated-characters/elf-archer-female.png",
  shade: "/assets/kenney-tiny-dungeon/Tiles/tile_0121.png",
  wolf: "/assets/kenney-tiny-dungeon/Tiles/tile_0124.png",
  spider: "/assets/kenney-tiny-dungeon/Tiles/tile_0120.png",
  slime: "/assets/kenney-tiny-dungeon/Tiles/tile_0108.png",
  brute: "/assets/kenney-tiny-dungeon/Tiles/tile_0122.png",
  cultist: "/assets/kenney-tiny-dungeon/Tiles/tile_0111.png",
  wraith: "/assets/kenney-tiny-dungeon/Tiles/tile_0123.png",
  demon: "/assets/kenney-tiny-dungeon/Tiles/tile_0110.png",
  knight: "/assets/kenney-tiny-dungeon/Tiles/tile_0096.png",
  boss: "/assets/kenney-tiny-dungeon/Tiles/tile_0110.png",
  bossLich: "/assets/kenney-tiny-dungeon/Tiles/tile_0084.png",
  bossSpider: "/assets/kenney-tiny-dungeon/Tiles/tile_0122.png",
  bossGolem: "/assets/kenney-tiny-dungeon/Tiles/tile_0096.png",
  bossDesert: "/assets/generated-bosses/desert-hesha.png",
  bossForest: "/assets/generated-bosses/forest-viloa.png",
  bossVolcano: "/assets/generated-bosses/volcano-charon.png",
  bossIce: "/assets/generated-bosses/ice-ur.png",
  bossTown: "/assets/generated-bosses/town-ryan.png",
  bossKing: "/assets/generated-bosses/demon-king-asmodeus.png",
  stageGrass: "/assets/kenney-tiny-battle/Tiles/tile_0000.png",
  stageGrassDetail: "/assets/kenney-tiny-battle/Tiles/tile_0001.png",
  stageFlowers: "/assets/kenney-tiny-battle/Tiles/tile_0002.png",
  stagePondLeft: "/assets/kenney-tiny-battle/Tiles/tile_0003.png",
  stagePondRight: "/assets/kenney-tiny-battle/Tiles/tile_0004.png",
  stageBuilding: "/assets/kenney-tiny-battle/Tiles/tile_0009.png",
  stageFountain: "/assets/kenney-tiny-battle/Tiles/tile_0014.png",
  stageTree: "/assets/kenney-tiny-battle/Tiles/tile_0094.png",
  stageRoad: "/assets/kenney-tiny-battle/Tiles/tile_0108.png",
  stageRoadCorner: "/assets/kenney-tiny-battle/Tiles/tile_0109.png",
  axe: "/assets/kenney-tiny-dungeon/Tiles/tile_0118.png",
  bat: "/assets/kenney-tiny-dungeon/Tiles/tile_0120.png",
  summonGuard: "/assets/generated-necromancy/skeleton-guard.png",
  summonMage: "/assets/dawnlike-necromancy/bone-mage.png",
  summonWraith: "/assets/dawnlike-necromancy/wraith.png",
  summonGolem: "/assets/dawnlike-necromancy/grave-golem.png",
  summonArcher: "/assets/dawnlike-necromancy/bone-archer.png",
  summonKnight: "/assets/dawnlike-necromancy/death-knight.png",
  summonDragon: "/assets/generated-necromancy/bone-dragon.png",
  summonLegion: "/assets/class-ultimates/death-legion-warrior.png",
  vfxWhip: "/assets/kenney-particle-pack/PNG/slash_02.png",
  vfxFlame: "/assets/kenney-particle-pack/PNG/flame_02.png",
  vfxBeam: "/assets/kenney-particle-pack/PNG/trace_04.png",
  vfxRing: "/assets/kenney-particle-pack/PNG/circle_03.png",
  vfxMagic: "/assets/kenney-particle-pack/PNG/magic_02.png",
  vfxMist: "/assets/kenney-particle-pack/PNG/smoke_07.png",
  vfxShock: "/assets/kenney-particle-pack/PNG/light_02.png",
  vfxHeal: "/assets/kenney-particle-pack/PNG/magic_05.png",
  vfxSpark: "/assets/kenney-particle-pack/PNG/spark_02.png",
  vfxStar: "/assets/kenney-particle-pack/PNG/star_02.png",
  vfxTwirl: "/assets/kenney-particle-pack/PNG/twirl_01.png",
  vfxFlare: "/assets/kenney-particle-pack/PNG/flare_01.png",
  vfxSymbol: "/assets/kenney-particle-pack/PNG/symbol_01.png",
  vfxScorch: "/assets/kenney-particle-pack/PNG/scorch_02.png",
  vfxMetalSlash: "/assets/kenney-particle-pack/PNG/slash_04.png",
  vfxMetalScratch: "/assets/kenney-particle-pack/PNG/scratch_01.png",
  vfxMetalTrace: "/assets/kenney-particle-pack/PNG/trace_01.png",
  vfxWoodRune: "/assets/kenney-particle-pack/PNG/symbol_02.png",
  vfxWoodTwirl: "/assets/kenney-particle-pack/PNG/twirl_03.png",
  vfxWoodSmoke: "/assets/kenney-particle-pack/PNG/smoke_06.png",
  vfxWaterRing: "/assets/kenney-particle-pack/PNG/circle_05.png",
  vfxWaterMagic: "/assets/kenney-particle-pack/PNG/magic_01.png",
  vfxWaterTrace: "/assets/kenney-particle-pack/PNG/trace_07.png",
  vfxFireCore: "/assets/kenney-particle-pack/PNG/fire_02.png",
  vfxFireTrail: "/assets/kenney-particle-pack/PNG/flame_06.png",
  vfxFireScorch: "/assets/kenney-particle-pack/PNG/scorch_03.png",
  vfxEarthDust: "/assets/kenney-particle-pack/PNG/dirt_03.png",
  vfxEarthCrack: "/assets/kenney-particle-pack/PNG/dirt_01.png",
  vfxEarthRing: "/assets/kenney-particle-pack/PNG/circle_04.png",
  elementMetalBlade: "/assets/generated-elements/metal-flying-sword.png",
  elementWoodRoots: "/assets/generated-elements/wood-root-cage.png",
  elementWaterCrest: "/assets/generated-elements/water-frost-wave.png",
  elementFireMeteor: "/assets/generated-elements/fire-meteor.png",
  elementEarthSpikes: "/assets/generated-elements/earth-stone-spikes.png",
  elementComboForestInferno: "/assets/generated-elements/combo-forest-inferno.png",
  elementComboMagmaEruption: "/assets/generated-elements/combo-magma-eruption.png",
  elementComboBladeArray: "/assets/generated-elements/combo-blade-array.png",
  elementComboFrozenBladeRain: "/assets/generated-elements/combo-frozen-blade-rain.png",
  elementComboTidalVines: "/assets/generated-elements/combo-tidal-vines.png",
  paladinFlameSword: "/assets/generated-class-skills/paladin-flame-sword.png",
  paladinHolyStaff: "/assets/generated-class-skills/paladin-holy-staff.png",
  paladinFrostShield: "/assets/generated-class-skills/paladin-frost-shield.png",
  paladinAegis: "/assets/generated-class-skills/paladin-aegis.png",
  paladinSanctuary: "/assets/generated-class-skills/paladin-sanctuary.png",
  paladinLance: "/assets/generated-class-skills/paladin-lance.png",
  rangerThunderBoomerang: "/assets/generated-class-skills/ranger-thunder-boomerang.png",
  rangerChainArrow: "/assets/generated-class-skills/ranger-chain-arrow.png",
  rangerVolley: "/assets/generated-class-skills/ranger-volley.png",
  rangerWindArrow: "/assets/generated-class-skills/ranger-wind-arrow.png",
  rangerTrap: "/assets/generated-class-skills/ranger-trap.png",
  rangerFalcon: "/assets/generated-class-skills/ranger-falcon.png",
  rangerRicochet: "/assets/generated-class-skills/ranger-ricochet.png",
  necromancerPortal: "/assets/generated-class-skills/necromancer-portal.png",
  mageYinWheel: "/assets/generated-class-skills/mage-yin-wheel.png",
  mageYangSeal: "/assets/generated-class-skills/mage-yang-seal.png",
  elfLongArrow: "/assets/generated-class-skills/elf-long-arrow.png",
  elfMoonArrow: "/assets/generated-class-skills/elf-moon-arrow.png",
  elfVineArrow: "/assets/generated-class-skills/elf-vine-arrow.png",
  elfSpiritHawk: "/assets/generated-class-skills/elf-spirit-hawk.png",
  elfLeafStorm: "/assets/generated-class-skills/elf-leaf-storm.png",
  elfStarTrap: "/assets/generated-class-skills/elf-star-trap.png",
  elfAncientBow: "/assets/generated-class-skills/elf-ancient-bow.png",
  vfxSoul: "/assets/kenney-particle-pack/PNG/magic_03.png",
  vfxSoulStar: "/assets/kenney-particle-pack/PNG/star_07.png",
  vfxBatSmoke: "/assets/kenney-particle-pack/PNG/smoke_04.png",
  vfxBatAura: "/assets/kenney-particle-pack/PNG/twirl_02.png",
  vfxThunderTrace: "/assets/kenney-particle-pack/PNG/trace_06.png",
  vfxThunderSpark: "/assets/kenney-particle-pack/PNG/spark_06.png",
  vfxPlagueSmoke: "/assets/kenney-particle-pack/PNG/smoke_09.png",
  vfxPlagueMagic: "/assets/kenney-particle-pack/PNG/magic_04.png",
  vfxMeteorFlame: "/assets/kenney-particle-pack/PNG/flame_05.png",
  vfxMeteorScorch: "/assets/kenney-particle-pack/PNG/scorch_01.png",
  vfxShield: "/assets/kenney-particle-pack/PNG/window_01.png",
  vfxConsecrate: "/assets/kenney-particle-pack/PNG/light_01.png",
  vfxLance: "/assets/kenney-particle-pack/PNG/trace_02.png",
  vfxVolley: "/assets/kenney-particle-pack/PNG/muzzle_01.png",
  vfxWindshot: "/assets/kenney-particle-pack/PNG/trace_03.png",
  vfxTrap: "/assets/kenney-particle-pack/PNG/window_02.png",
  vfxFalcon: "/assets/kenney-particle-pack/PNG/star_01.png",
  vfxRicochet: "/assets/kenney-particle-pack/PNG/spark_01.png",
  vfxBones: "/assets/kenney-particle-pack/PNG/trace_05.png",
  vfxSkeletons: "/assets/kenney-particle-pack/PNG/smoke_01.png",
  vfxCurse: "/assets/kenney-particle-pack/PNG/window_03.png",
  vfxYin: "/assets/kenney-particle-pack/PNG/circle_01.png",
  vfxYang: "/assets/kenney-particle-pack/PNG/circle_02.png",
  vfxElvenArrow: "/assets/kenney-particle-pack/PNG/muzzle_02.png",
  vfxMoonArrow: "/assets/kenney-particle-pack/PNG/star_03.png",
  vfxVineArrow: "/assets/kenney-particle-pack/PNG/dirt_02.png",
  vfxSpiritHawk: "/assets/kenney-particle-pack/PNG/star_04.png",
  vfxLeafStorm: "/assets/kenney-particle-pack/PNG/smoke_02.png",
  vfxStarTrap: "/assets/kenney-particle-pack/PNG/window_04.png",
  vfxAncientBow: "/assets/kenney-particle-pack/PNG/muzzle_03.png",
  ultimatePaladin: "/assets/class-ultimates/paladin-heavenly-judgement.png",
  ultimateRanger: "/assets/class-ultimates/ranger-arrow-tempest.png",
  ultimateNecromancer: "/assets/class-ultimates/necromancer-bone-gate.png",
  ultimateMage: "/assets/class-ultimates/mage-five-elements.png",
  ultimateElf: "/assets/class-ultimates/elf-world-tree-eclipse.png",
  ultimateAltar: "/assets/class-ultimates/purple-altar-v2.png",
} as const;

export type NightfallSprite = keyof typeof NIGHTFALL_SPRITES;

export class NightfallAssets {
  private images = new Map<NightfallSprite, HTMLImageElement>();

  constructor() {
    (Object.entries(NIGHTFALL_SPRITES) as Array<[NightfallSprite, string]>).forEach(([id, path]) => {
      const image = new Image();
      image.src = path;
      this.images.set(id, image);
    });
  }

  get(id: NightfallSprite) {
    const image = this.images.get(id);
    return image?.complete && image.naturalWidth > 0 ? image : null;
  }
}
