import type { CharacterId, EvolutionId, PassiveId, TarotId, WeaponId } from "./types";

export const WEAPONS: Record<WeaponId, { name: string; icon: string; damage: number; cooldown: number; description: string }> = {
  whip: { name: "灼热圣剑", icon: "†", damage: 10, cooldown: 0.8, description: "向面前进行120°近战圣焰挥砍" },
  boomerang: { name: "雷霆回旋镖", icon: "➤", damage: 15, cooldown: 1.2, description: "投出可穿透并返回的雷电回旋镖" },
  holy: { name: "圣光之杖", icon: "✦", damage: 25, cooldown: 2.5, description: "在敌人密集处降下圣光柱" },
  frost: { name: "寒铁守护", icon: "❄", damage: 8, cooldown: 1.8, description: "以寒铁圣力冻结并击退近身敌人" },
  bats: { name: "召唤蝙蝠", icon: "◆", damage: 6, cooldown: 2.2, description: "初始召唤4只追踪敌人的暗影蝙蝠" },
  axes: { name: "旋转飞斧", icon: "⚔", damage: 20, cooldown: 1.5, description: "召唤环绕角色旋转的重型飞斧" },
  soul: { name: "灵魂飞弹", icon: "◈", damage: 12, cooldown: 0.9, description: "发射自动追踪敌人的幽魂弹" },
  meteor: { name: "冥火坠星", icon: "☄", damage: 18, cooldown: 2.1, description: "从冥界裂隙降下亡者之火" },
  chain: { name: "雷羽连锁箭", icon: "ϟ", damage: 10, cooldown: 1.35, description: "雷箭在多个邻近敌人之间跳跃" },
  plague: { name: "瘟疫足迹", icon: "☣", damage: 5, cooldown: 0.75, description: "移动时留下持续3秒、按生命比例伤害敌人的毒雾" },
  metal: { name: "金刃术", icon: "◇", damage: 18, cooldown: 1.1, description: "召唤高速金属飞刃斩击远处敌人" },
  wood: { name: "青木缠绕", icon: "♣", damage: 12, cooldown: 1.6, description: "在敌群脚下降下藤蔓并持续减速" },
  water: { name: "玄水冰瀑", icon: "≈", damage: 14, cooldown: 1.25, description: "在远处敌群中爆发寒潮并冻结敌人" },
  fire: { name: "离火流星", icon: "♨", damage: 22, cooldown: 1.8, description: "从天而降的远程火焰流星" },
  earth: { name: "厚土震击", icon: "▰", damage: 26, cooldown: 2.2, description: "在敌群中心引发大地震击并击退敌人" },
  shield: { name: "圣盾回响", icon: "⬡", damage: 14, cooldown: 1.7, description: "圣盾环身爆发并强力击退近身敌人" },
  consecrate: { name: "奉献圣域", icon: "✛", damage: 12, cooldown: 2.25, description: "脚下展开可减速敌人并治疗自身的圣域" },
  lance: { name: "裁决枪阵", icon: "‡", damage: 24, cooldown: 1.65, description: "连续召下圣枪贯穿最近的敌人" },
  volley: { name: "疾风箭雨", icon: "➵", damage: 11, cooldown: .9, description: "向前方扇形射出一轮高速箭矢" },
  windshot: { name: "破空强弓", icon: "➶", damage: 22, cooldown: 1.45, description: "射出高速贯穿并击退敌人的风矢" },
  trap: { name: "猎手陷阱", icon: "⌗", damage: 15, cooldown: 2.15, description: "在敌群脚下布置减速陷阱" },
  falcon: { name: "战隼突袭", icon: "⌁", damage: 17, cooldown: 1.35, description: "召唤自动追踪敌人的战隼" },
  ricochet: { name: "弹射飞刃", icon: "⌁", damage: 12, cooldown: 1.15, description: "飞刃在多个目标之间快速弹射" },
  bones: { name: "白骨枪林", icon: "⌇", damage: 14, cooldown: 1.2, description: "向前方射出可贯穿敌人的骨枪" },
  skeletons: { name: "骸骨军团", icon: "♙", damage: 9, cooldown: 1.5, description: "召唤数名追猎敌人的骸骨战士" },
  curse: { name: "凋零诅咒", icon: "☾", damage: 19, cooldown: 2.05, description: "在敌群中引爆减速诅咒" },
  skeletonGuard: { name: "骷髅卫兵", icon: "♙", damage: 13, cooldown: 4.6, description: "召唤持盾卫兵近身追击并替你撕开敌阵" },
  boneMage: { name: "骷髅法师", icon: "♝", damage: 17, cooldown: 5.2, description: "召唤骸骨法师在后方发射追踪亡魂弹" },
  wraithSummon: { name: "怨灵召来", icon: "◌", damage: 11, cooldown: 4.2, description: "召唤能够穿过敌群、造成范围伤害的怨灵" },
  graveGolem: { name: "墓穴魔像", icon: "♜", damage: 27, cooldown: 7.4, description: "唤醒高伤、强击退且持续时间很长的墓穴魔像" },
  boneArchers: { name: "骷髅弓手", icon: "➴", damage: 14, cooldown: 5.6, description: "召唤两名骷髅弓手在远处进行亡骨齐射" },
  deathKnight: { name: "死亡骑士", icon: "♞", damage: 24, cooldown: 7, description: "召唤高速追猎并施展范围斩击的死亡骑士" },
  yin: { name: "玄阴轮", icon: "◐", damage: 13, cooldown: 1.75, description: "释放环身玄阴之力冻结近身敌人" },
  yang: { name: "曜阳印", icon: "◉", damage: 20, cooldown: 2, description: "在敌阵中连续降下曜阳法印" },
  elvenArrow: { name: "翠风长箭", icon: "➹", damage: 24, cooldown: 1.1, description: "射出极高速、可连续贯穿目标的精灵箭" },
  moonArrow: { name: "月华箭雨", icon: "☽", damage: 13, cooldown: 1.8, description: "月光箭从天空连续落向敌群" },
  vineArrow: { name: "荆棘束缚箭", icon: "♧", damage: 15, cooldown: 1.55, description: "命中多个敌人并以藤蔓长时间减速" },
  spiritHawk: { name: "翡翠灵鹰", icon: "⌁", damage: 18, cooldown: 1.4, description: "召唤翡翠灵鹰自动追猎敌人" },
  leafStorm: { name: "千叶风暴", icon: "❧", damage: 12, cooldown: 1.65, description: "叶刃风暴环绕自身并击退敌人" },
  starTrap: { name: "星辉猎阵", icon: "✧", damage: 16, cooldown: 2.2, description: "布下能够冻结敌人的精灵星阵" },
  ancientBow: { name: "古树巨弓", icon: "➳", damage: 10, cooldown: 1.3, description: "一次射出五支带有穿透力的古树箭" },
};

export const PASSIVES: Record<PassiveId, { name: string; icon: string; description: string }> = {
  might: { name: "力量徽章", icon: "✹", description: "每级伤害 +5%" },
  boots: { name: "疾风之靴", icon: "➟", description: "每级移动速度 +8%" },
  vitality: { name: "生命护符", icon: "♥", description: "每级最大生命 +20" },
  greed: { name: "贪婪之环", icon: "◉", description: "每级拾取范围 +30%" },
  armor: { name: "护甲片", icon: "⬢", description: "每级受到伤害 -1" },
  cooldown: { name: "冷却石", icon: "⌛", description: "每级技能冷却 -10%" },
};

export const EVOLUTIONS: Record<WeaponId, { passive: PassiveId; id: EvolutionId; name: string; description: string }> = {
  whip: { passive: "might", id: "flameWhip", name: "烈焰裁决剑", description: "剑气范围翻倍，灼烧伤害提升至10/秒" },
  boomerang: { passive: "boots", id: "thunderstorm", name: "雷霆万钧", description: "同时投掷3枚自动追踪回旋镖" },
  holy: { passive: "cooldown", id: "judgement", name: "神圣审判", description: "每次连续降下3道圣光" },
  frost: { passive: "armor", id: "absoluteZero", name: "绝对零度", description: "释放持续3秒、减速50%的冰雾" },
  bats: { passive: "greed", id: "batSwarm", name: "蝙蝠群袭", description: "蝙蝠增至6只，并集中强化伤害与生命" },
  axes: { passive: "vitality", id: "deathCyclone", name: "死亡旋风", description: "巨斧扩大并产生强力击退" },
  soul: { passive: "vitality", id: "soulTempest", name: "亡魂风暴", description: "持续发射五枚可穿透的追踪亡魂" },
  meteor: { passive: "might", id: "apocalypse", name: "天火灭世", description: "每轮降下五枚巨型陨星" },
  chain: { passive: "cooldown", id: "thunderDomain", name: "雷神领域", description: "雷霆连锁数量翻倍并产生爆炸" },
  plague: { passive: "armor", id: "plagueSky", name: "瘟疫天幕", description: "毒雾范围扩大50%，百分比伤害提升" },
  metal: { passive: "cooldown", id: "metalStorm", name: "万刃归宗", description: "同时锁定五名敌人，金刃必定穿透" },
  wood: { passive: "greed", id: "ancientForest", name: "万木森罗", description: "藤蔓领域扩大并延长束缚时间" },
  water: { passive: "armor", id: "deepSea", name: "沧海凝冰", description: "连续产生三次冰瀑并冻结更久" },
  fire: { passive: "might", id: "solarFlame", name: "太阳真火", description: "连续降下五枚大型离火流星" },
  earth: { passive: "vitality", id: "mountainFall", name: "山岳天倾", description: "震击范围翻倍并产生强力击退" },
  shield: { passive: "armor", id: "aegis", name: "不灭圣盾", description: "圣盾范围扩大并连续产生两次回响" },
  consecrate: { passive: "vitality", id: "holyGround", name: "天国圣域", description: "圣域范围扩大并显著提升治疗" },
  lance: { passive: "might", id: "heavenLance", name: "天穹裁决", description: "圣枪数量翻倍并贯穿更多敌人" },
  volley: { passive: "cooldown", id: "arrowStorm", name: "万箭风暴", description: "扇形箭数量翻倍且冷却更短" },
  windshot: { passive: "might", id: "tempestShot", name: "暴风破城矢", description: "箭矢巨大化并产生强力击退" },
  trap: { passive: "greed", id: "hunterDomain", name: "猎王领域", description: "同时布置更多大型陷阱" },
  falcon: { passive: "boots", id: "stormFalcon", name: "雷霆战隼", description: "召唤三只高速战隼" },
  ricochet: { passive: "cooldown", id: "infiniteRicochet", name: "无限弹射", description: "飞刃弹射次数和目标数量翻倍" },
  bones: { passive: "armor", id: "boneLegion", name: "白骨王座", description: "骨枪数量翻倍并拥有更强穿透" },
  skeletons: { passive: "vitality", id: "deathArmy", name: "亡者大军", description: "召唤更多持续更久的骸骨战士" },
  curse: { passive: "cooldown", id: "eternalCurse", name: "永夜凋零", description: "诅咒范围扩大并延长减速" },
  skeletonGuard: { passive: "armor", id: "royalGuard", name: "不死王卫", description: "卫兵升格为王卫，生命、伤害和盾击范围全面提升" },
  boneMage: { passive: "cooldown", id: "lichCouncil", name: "巫妖议会", description: "骷髅法师升格为巫妖首席，强化追踪亡魂齐射" },
  wraithSummon: { passive: "greed", id: "wraithHost", name: "百鬼夜行", description: "怨灵凝聚为高阶魂体，穿行时留下灵魂爆破" },
  graveGolem: { passive: "vitality", id: "ossuaryTitan", name: "骸骨泰坦", description: "魔像巨大化，重击会震荡整片敌群" },
  boneArchers: { passive: "might", id: "deadeyeVolley", name: "亡者箭阵", description: "两名弓手强化射程与火力，并发射贯穿骨箭" },
  deathKnight: { passive: "boots", id: "dreadCavalier", name: "恐惧领主", description: "死亡骑士升格为恐惧领主并发动高速连斩" },
  yin: { passive: "armor", id: "lunarVoid", name: "太阴归墟", description: "玄阴轮扩大并冻结更久" },
  yang: { passive: "might", id: "solarCrown", name: "太阳神印", description: "曜阳印数量和爆炸范围提升" },
  elvenArrow: { passive: "boots", id: "worldTreeArrow", name: "世界树神箭", description: "箭矢贯穿全场且获得额外伤害" },
  moonArrow: { passive: "cooldown", id: "moonRain", name: "永恒月雨", description: "月光箭数量翻倍并扩大落点" },
  vineArrow: { passive: "greed", id: "thornHeart", name: "荆棘之心", description: "束缚目标增加并延长减速" },
  spiritHawk: { passive: "boots", id: "emeraldHawk", name: "翡翠鹰群", description: "同时召唤三只翡翠灵鹰" },
  leafStorm: { passive: "might", id: "autumnTempest", name: "万叶天岚", description: "叶刃风暴巨大化并强力击退" },
  starTrap: { passive: "armor", id: "astralSnare", name: "群星猎场", description: "星阵数量增加并冻结更久" },
  ancientBow: { passive: "vitality", id: "sylvanBallista", name: "森灵弩炮", description: "箭阵数量、体积和穿透全面提升" },
};

export const TAROTS: Record<TarotId, { numeral: string; name: string; icon: string; description: string }> = {
  mage: { numeral: "Ⅰ", name: "法师", icon: "✦", description: "拾取经验宝石时发射追踪飞弹" },
  emperor: { numeral: "Ⅳ", name: "皇帝", icon: "♛", description: "静止1.5秒获得护盾并恢复30%生命" },
  lovers: { numeral: "Ⅵ", name: "恋人", icon: "♥", description: "移动时每秒恢复2点生命" },
  hermit: { numeral: "Ⅸ", name: "隐者", icon: "☼", description: "升级后8秒内伤害和移速提升30%" },
  tower: { numeral: "ⅩⅥ", name: "高塔", icon: "♜", description: "受击时释放全屏真实伤害冲击波" },
  fool: { numeral: "ⅩⅫ", name: "愚者", icon: "★", description: "每击杀100只敌人补全一件未拥有道具" },
};

export const CHARACTERS: Record<CharacterId, { name: string; title: string; icon: string; weapon: WeaponId; hpMultiplier: number; speedMultiplier: number; cooldownBonus: number; damageMultiplier: number; description: string }> = {
  paladin: { name: "圣骑士", title: "余烬守望者", icon: "♜", weapon: "whip", hpMultiplier: 1.3, speedMultiplier: 0.9, cooldownBonus: 0, damageMultiplier: 1, description: "每秒恢复0.5HP，生命+30%，移速-10%" },
  ranger: { name: "游侠", title: "雷羽追猎者", icon: "➶", weapon: "boomerang", hpMultiplier: 1, speedMultiplier: 1.2, cooldownBonus: 0, damageMultiplier: 0.85, description: "暴击率+10%，移速+20%，攻击-15%" },
  necromancer: { name: "死灵法师", title: "夜群召唤者", icon: "☠", weapon: "bats", hpMultiplier: 0.8, speedMultiplier: 1, cooldownBonus: 0.15, damageMultiplier: 1, description: "召唤物生命+20%，冷却-15%，角色生命-20%" },
  mage: { name: "元素法师", title: "五行御术者", icon: "☯", weapon: "fire", hpMultiplier: 0.85, speedMultiplier: 1.05, cooldownBonus: 0.1, damageMultiplier: 1.22, description: "按五行相生触发高伤连携，操作最难、伤害上限最高，生命-15%" },
  elf: { name: "精灵弓箭手", title: "翡翠林地守望者", icon: "➹", weapon: "elvenArrow", hpMultiplier: 0.9, speedMultiplier: 1.18, cooldownBonus: 0.08, damageMultiplier: 1, description: "移速+18%，冷却-8%，生命-10%" },
};

export const LEVEL_DAMAGE = [0, 1, 1.2, 1.45, 1.75, 2.2];
export const LEVEL_COOLDOWN = [0, 0, 0.08, 0.16, 0.28, 0.4];
export const LEVEL_SIZE = [0, 1, 1.1, 1.25, 1.4, 1.65];

export const xpForLevel = (level: number) => Math.round(28 * Math.pow(level, 1.4));
