import { gameAudio } from "@/lib/audio/gameAudio";
import { BOARD_RIGHT, createPegs, createWave, PEG_HEIGHT, PEG_WIDTH, UPGRADES } from "./data";
import { pegDamage, reducedAttack, upgradeChoices } from "./rules";
import type { Ball, Peg, RuneEnemy, RunePegCallbacks, RunePegStatus, RuneUpgradeId } from "./types";

type Particle={x:number;y:number;vx:number;vy:number;life:number;color:string};

export class RunePegEngine{
  private context:CanvasRenderingContext2D;private animation=0;private lastTime=0;private lastHud=0;private status:RunePegStatus="idle";private beforePause:RunePegStatus="aiming";
  private pegs:Peg[]=createPegs();private balls:Ball[]=[];private particles:Particle[]=[];private enemies:RuneEnemy[]=createWave(1);private wave=1;private hp=72;private maxHp=72;private score=0;private shot=0;private shotDamage=0;private hitCount=0;
  private aimX=330;private aimY=310;private power=0;private echo=0;private blast=0;private armor=0;private prism=false;private relics:RuneUpgradeId[]=[];private phaseTimer=0;private shake=0;private message="移动准线，点击发射";
  constructor(private canvas:HTMLCanvasElement,private callbacks:RunePegCallbacks){this.context=canvas.getContext("2d")!;this.resize();}
  resize(){const ratio=Math.min(2,window.devicePixelRatio||1);this.canvas.width=PEG_WIDTH*ratio;this.canvas.height=PEG_HEIGHT*ratio;this.context.setTransform(ratio,0,0,ratio,0,0);this.draw();}
  destroy(){cancelAnimationFrame(this.animation);}
  start(){this.pegs=createPegs();this.balls=[];this.particles=[];this.enemies=createWave(1);this.wave=1;this.hp=72;this.maxHp=72;this.score=0;this.shot=0;this.shotDamage=0;this.hitCount=0;this.power=0;this.echo=0;this.blast=0;this.armor=0;this.prism=false;this.relics=[];this.status="aiming";this.message="移动准线，点击发射";this.lastTime=performance.now();cancelAnimationFrame(this.animation);this.animation=requestAnimationFrame(this.tick);gameAudio.play("start");this.callbacks.onStatus("aiming",0,"");this.emitHud(true);}
  aim(clientX:number,clientY:number){const rect=this.canvas.getBoundingClientRect();this.aimX=(clientX-rect.left)/rect.width*PEG_WIDTH;this.aimY=(clientY-rect.top)/rect.height*PEG_HEIGHT;this.aimX=Math.max(85,Math.min(BOARD_RIGHT-35,this.aimX));this.aimY=Math.max(125,this.aimY);}
  shoot(){if(this.status!=="aiming")return;const ox=330,oy=82;let dx=this.aimX-ox,dy=Math.max(50,this.aimY-oy);const length=Math.hypot(dx,dy)||1;dx/=length;dy/=length;this.balls=[];const count=Math.min(3,1+this.echo);for(let index=0;index<count;index+=1){const spread=(index-(count-1)/2)*.12;const cos=Math.cos(spread),sin=Math.sin(spread);this.balls.push({x:ox,y:oy,vx:(dx*cos-dy*sin)*385,vy:(dx*sin+dy*cos)*385,trail:[]});}this.pegs.forEach(peg=>{peg.lit=false;});this.shot+=1;this.shotDamage=0;this.hitCount=0;this.status="rolling";this.message="弹珠正在点亮符文";gameAudio.play("drop");this.callbacks.onStatus("rolling",this.score,"");this.emitHud(true);}
  chooseUpgrade(id:RuneUpgradeId){if(this.status!=="upgrade")return;this.relics.push(id);if(id==="power")this.power+=1;if(id==="echo")this.echo=Math.min(2,this.echo+1);if(id==="blast")this.blast+=10;if(id==="armor")this.armor+=1;if(id==="prism")this.prism=true;if(id==="heal"){this.maxHp+=6;this.hp=Math.min(this.maxHp,this.hp+22);}this.wave+=1;this.enemies=createWave(this.wave);this.pegs=createPegs();this.status="aiming";this.message=`第 ${this.wave} 波：${this.enemies[0].name}`;this.callbacks.onStatus("aiming",this.score,"");gameAudio.play("start");this.emitHud(true);}
  togglePause(){if(this.status==="paused"){this.status=this.beforePause;this.lastTime=performance.now();this.callbacks.onStatus(this.status,this.score,"");return;}if(this.status==="aiming"||this.status==="rolling"){this.beforePause=this.status;this.status="paused";this.callbacks.onStatus("paused",this.score,"");this.draw();}}
  private tick=(time:number)=>{const delta=Math.min(.033,Math.max(0,(time-this.lastTime)/1000));this.lastTime=time;if(this.status==="rolling")this.update(delta);else if(this.status!=="paused")this.updateParticles(delta);this.draw();if(["aiming","rolling","paused","upgrade"].includes(this.status))this.animation=requestAnimationFrame(this.tick);};
  private update(delta:number){this.phaseTimer+=delta;this.shake=Math.max(0,this.shake-delta);const steps=3;for(let step=0;step<steps;step+=1)this.physics(delta/steps);this.updateParticles(delta);if(this.balls.length===0)this.resolveShot();this.emitHud(false);}
  private physics(delta:number){for(const ball of this.balls){ball.vy+=510*delta;ball.x+=ball.vx*delta;ball.y+=ball.vy*delta;if(ball.x<25+10){ball.x=35;ball.vx=Math.abs(ball.vx)*.9;}if(ball.x>BOARD_RIGHT-10){ball.x=BOARD_RIGHT-10;ball.vx=-Math.abs(ball.vx)*.9;}ball.trail.push({x:ball.x,y:ball.y});if(ball.trail.length>10)ball.trail.shift();for(const peg of this.pegs){if(peg.consumed)continue;const dx=ball.x-peg.x,dy=ball.y-peg.y;const dist2=dx*dx+dy*dy;if(dist2>22*22||dist2<.01)continue;const distance=Math.sqrt(dist2),nx=dx/distance,ny=dy/distance;ball.x=peg.x+nx*22;ball.y=peg.y+ny*22;const dot=ball.vx*nx+ball.vy*ny;if(dot<0){ball.vx-=1.88*dot*nx;ball.vy-=1.88*dot*ny;ball.vx*=.985;ball.vy*=.985;}if(!peg.lit)this.hitPeg(peg);}}
    this.balls=this.balls.filter(ball=>ball.y<PEG_HEIGHT+34&&Math.abs(ball.vx)+Math.abs(ball.vy)>12);
  }
  private hitPeg(peg:Peg){peg.lit=true;this.hitCount+=1;let damage=pegDamage(peg.kind,this.power,this.blast);if(this.prism&&this.hitCount%7===0){damage+=16;this.spawn(peg.x,peg.y,"#f5e77b",18);gameAudio.play("perfect");}this.shotDamage+=damage;this.score+=damage*7;const color=peg.kind==="bomb"?"#ff795d":peg.kind==="critical"?"#ffe06d":peg.kind==="refresh"?"#70e6bd":"#78c9ff";this.spawn(peg.x,peg.y,color,peg.kind==="bomb"?20:7);if(peg.kind==="bomb"){peg.consumed=true;for(const other of this.pegs){if(other.lit||other.consumed)continue;const dx=other.x-peg.x,dy=other.y-peg.y;if(dx*dx+dy*dy<(this.blast?118:92)**2){other.lit=true;this.shotDamage+=4+this.power;this.score+=(4+this.power)*5;this.spawn(other.x,other.y,"#ffb267",4);}}this.shake=.2;gameAudio.play("crash");}else if(peg.kind==="refresh"){this.pegs.forEach(item=>{if(item.kind!=="bomb")item.lit=false;});gameAudio.play("match");}else gameAudio.play(peg.kind==="critical"?"great":"tap");}
  private resolveShot(){if(this.status!=="rolling")return;let damage=this.shotDamage;while(damage>0&&this.enemies.length){const enemy=this.enemies[0];const dealt=Math.min(enemy.hp,damage);enemy.hp-=dealt;damage-=dealt;this.score+=dealt*10;if(enemy.hp<=0){this.score+=300*this.wave;this.spawn(808,260,enemy.color,30);this.enemies.shift();gameAudio.play("win");}}
    if(this.enemies.length===0){if(this.wave>=3){this.finish("won","星门守卫已经粉碎");return;}this.status="upgrade";const choices=upgradeChoices(UPGRADES,this.relics,this.wave);this.callbacks.onUpgrade(choices);this.callbacks.onStatus("upgrade",this.score,"选择一枚遗物");this.message="战利品：选择一枚遗物";this.emitHud(true);return;}
    const enemy=this.enemies[0];const incoming=reducedAttack(enemy.attack,this.armor);this.hp=Math.max(0,this.hp-incoming);this.shake=.18;gameAudio.play("mismatch");if(this.hp<=0){this.finish("lost",`${enemy.name} 击碎了你的符文核心`);return;}this.pegs=this.pegs.map(peg=>({...peg,lit:false}));this.status="aiming";this.message=`造成 ${this.shotDamage} 伤害，受到 ${incoming} 点反击`;this.callbacks.onStatus("aiming",this.score,"");this.emitHud(true);
  }
  private finish(status:"won"|"lost",message:string){this.status=status;this.callbacks.onStatus(status,this.score,message);this.emitHud(true);gameAudio.play(status==="won"?"win":"miss");}
  private spawn(x:number,y:number,color:string,count:number){for(let i=0;i<count&&this.particles.length<150;i+=1){const angle=i/count*Math.PI*2;this.particles.push({x,y,vx:Math.cos(angle)*(35+i%5*16),vy:Math.sin(angle)*(35+i%4*14),life:.65,color});}}
  private updateParticles(delta:number){for(const p of this.particles){p.life-=delta;p.x+=p.vx*delta;p.y+=p.vy*delta;p.vy+=70*delta;}this.particles=this.particles.filter(p=>p.life>0);}
  private emitHud(force:boolean){const now=performance.now();if(!force&&now-this.lastHud<90)return;this.lastHud=now;const enemy=this.enemies[0];this.callbacks.onHud({score:this.score,wave:this.wave,totalWaves:3,hp:this.hp,maxHp:this.maxHp,damage:this.shotDamage,shot:this.shot,message:this.message,enemyName:enemy?.name??"已击败",enemyHp:enemy?.hp??0,enemyMaxHp:enemy?.maxHp??1,relics:this.relics.map(id=>UPGRADES.find(item=>item.id===id)?.icon??"◆")});}
  private draw(){const c=this.context;c.save();if(this.shake>0)c.translate((Math.random()-.5)*8,(Math.random()-.5)*6);const bg=c.createLinearGradient(0,0,0,PEG_HEIGHT);bg.addColorStop(0,"#17223e");bg.addColorStop(.62,"#26385a");bg.addColorStop(1,"#11172b");c.fillStyle=bg;c.fillRect(-10,-10,PEG_WIDTH+20,PEG_HEIGHT+20);c.fillStyle="#ffffff08";for(let x=0;x<PEG_WIDTH;x+=48)c.fillRect(x,0,1,PEG_HEIGHT);for(let y=0;y<PEG_HEIGHT;y+=48)c.fillRect(0,y,PEG_WIDTH,1);this.drawBoard(c);this.drawEnemies(c);this.drawBalls(c);for(const p of this.particles){c.save();c.globalAlpha=Math.max(0,p.life/.65);c.fillStyle=p.color;c.shadowColor=p.color;c.shadowBlur=8;c.fillRect(p.x-3,p.y-3,6,6);c.restore();}c.restore();if(this.status==="paused"){c.fillStyle="#080d1edb";c.fillRect(0,0,PEG_WIDTH,PEG_HEIGHT);c.fillStyle="#fff";c.textAlign="center";c.font="700 32px Georgia";c.fillText("符文暂停",PEG_WIDTH/2,PEG_HEIGHT/2);}}
  private drawBoard(c:CanvasRenderingContext2D){c.fillStyle="#0d1428cc";c.strokeStyle="#7185b055";c.lineWidth=3;c.beginPath();c.roundRect(20,105,BOARD_RIGHT,420,20);c.fill();c.stroke();c.fillStyle="#15213c";c.fillRect(35,490,BOARD_RIGHT-55,25);for(let x=50;x<BOARD_RIGHT-20;x+=42){c.fillStyle=x%84?"#263b60":"#314a70";c.beginPath();c.moveTo(x,490);c.lineTo(x+32,490);c.lineTo(x+25,516);c.lineTo(x-7,516);c.closePath();c.fill();}
    for(const peg of this.pegs){if(peg.consumed)continue;const colors={normal:"#74bffc",critical:"#ffe16b",bomb:"#ff725e",refresh:"#6ce1b3"};const color=colors[peg.kind];c.save();c.globalAlpha=peg.lit?.45:1;c.fillStyle=color;c.shadowColor=color;c.shadowBlur=peg.lit?4:11;c.beginPath();c.arc(peg.x,peg.y,peg.kind==="bomb"?12:9,0,Math.PI*2);c.fill();c.strokeStyle="#eef8ff";c.lineWidth=2;c.stroke();if(peg.kind!=="normal"){c.fillStyle="#1a2034";c.textAlign="center";c.textBaseline="middle";c.font="700 11px sans-serif";c.fillText(peg.kind==="bomb"?"✹":peg.kind==="critical"?"×2":"↻",peg.x,peg.y+1);}c.restore();}
    c.fillStyle="#d9efff";c.beginPath();c.arc(330,76,22,0,Math.PI*2);c.fill();c.fillStyle="#4f6bc2";c.beginPath();c.arc(330,76,12,0,Math.PI*2);c.fill();if(this.status==="aiming"){const angle=Math.atan2(this.aimY-82,this.aimX-330);c.save();c.translate(330,82);c.rotate(angle);c.strokeStyle="#dff8ff99";c.lineWidth=3;c.setLineDash([9,8]);c.beginPath();c.moveTo(24,0);c.lineTo(130,0);c.stroke();c.setLineDash([]);c.fillStyle="#fff";c.beginPath();c.moveTo(140,0);c.lineTo(126,-7);c.lineTo(126,7);c.closePath();c.fill();c.restore();}}
  private drawBalls(c:CanvasRenderingContext2D){for(const ball of this.balls){ball.trail.forEach((point,index)=>{c.globalAlpha=(index+1)/ball.trail.length*.28;c.fillStyle="#8fe8ff";c.beginPath();c.arc(point.x,point.y,4+index*.3,0,Math.PI*2);c.fill();});c.globalAlpha=1;const fill=c.createRadialGradient(ball.x-4,ball.y-5,2,ball.x,ball.y,12);fill.addColorStop(0,"#fff");fill.addColorStop(.3,"#82ebff");fill.addColorStop(1,"#4c63d8");c.fillStyle=fill;c.shadowColor="#74ddff";c.shadowBlur=15;c.beginPath();c.arc(ball.x,ball.y,11,0,Math.PI*2);c.fill();c.shadowBlur=0;}}
  private drawEnemies(c:CanvasRenderingContext2D){const enemy=this.enemies[0];if(!enemy)return;const x=816,y=275;c.save();c.translate(x,y);c.shadowColor=enemy.color;c.shadowBlur=22;c.fillStyle=enemy.color;c.strokeStyle="#2a1731";c.lineWidth=5;if(enemy.kind==="slime"){c.beginPath();c.moveTo(-55,43);c.quadraticCurveTo(-64,-43,0,-56);c.quadraticCurveTo(64,-43,55,43);c.closePath();c.fill();c.stroke();}else if(enemy.kind==="golem"){c.fillRect(-50,-56,100,112);c.strokeRect(-50,-56,100,112);c.fillStyle="#f5b66a";c.fillRect(-68,-15,18,50);c.fillRect(50,-15,18,50);}else{c.beginPath();for(let i=0;i<10;i+=1){const a=-Math.PI/2+i*Math.PI/5,r=i%2?48:70;c.lineTo(Math.cos(a)*r,Math.sin(a)*r);}c.closePath();c.fill();c.stroke();c.fillStyle="#f5d36b";c.beginPath();c.arc(0,0,23,0,Math.PI*2);c.fill();}c.fillStyle="#15182a";c.beginPath();c.arc(-18,-6,6,0,Math.PI*2);c.arc(18,-6,6,0,Math.PI*2);c.fill();c.restore();c.fillStyle="#ffffff18";c.fillRect(733,380,166,10);c.fillStyle=enemy.color;c.fillRect(733,380,166*Math.max(0,enemy.hp/enemy.maxHp),10);c.strokeStyle="#ffffff55";c.strokeRect(733,380,166,10);c.fillStyle="#fff";c.textAlign="center";c.font="700 14px sans-serif";c.fillText(enemy.name,816,410);c.fillStyle="#a9bad8";c.font="11px sans-serif";c.fillText(`${enemy.hp} / ${enemy.maxHp}`,816,429);}
}
