"use client";
import {useEffect,useRef,useState} from "react";
import type{MiniGameProps}from"../types";
import{RunePegEngine}from"./Engine";
import type{RunePegHud,RunePegStatus,RuneUpgrade}from"./types";
import styles from"./RunePeg.module.css";
const INITIAL:RunePegHud={score:0,wave:1,totalWaves:3,hp:72,maxHp:72,damage:0,shot:0,message:"移动准线，点击发射",enemyName:"苔晶团子",enemyHp:58,enemyMaxHp:58,relics:[]};
export function RunePeg({bestScore,onScore}:MiniGameProps){const canvasRef=useRef<HTMLCanvasElement>(null),engineRef=useRef<RunePegEngine|null>(null),scoreRef=useRef(onScore);const[status,setStatus]=useState<RunePegStatus>("idle"),[hud,setHud]=useState(INITIAL),[result,setResult]=useState(""),[choices,setChoices]=useState<RuneUpgrade[]>([]);
  useEffect(()=>{scoreRef.current=onScore;},[onScore]);useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const engine=new RunePegEngine(canvas,{onHud:setHud,onUpgrade:setChoices,onStatus:(next,score,message)=>{setStatus(next);setResult(message);if(next==="won"||next==="lost")scoreRef.current(score);}});engineRef.current=engine;const resize=()=>engine.resize();const key=(e:KeyboardEvent)=>{if(e.code==="Space"){e.preventDefault();engine.shoot();}if(e.key.toLowerCase()==="p")engine.togglePause();};window.addEventListener("resize",resize);window.addEventListener("keydown",key);return()=>{engine.destroy();window.removeEventListener("resize",resize);window.removeEventListener("keydown",key);};},[]);
  return <div className={styles.game}><canvas ref={canvasRef} aria-label="符文弹珠战场" onPointerMove={e=>engineRef.current?.aim(e.clientX,e.clientY)} onPointerDown={e=>{engineRef.current?.aim(e.clientX,e.clientY);engineRef.current?.shoot();}}/>
    {status!=="idle"&&<><div className={styles.hud}><div className={styles.panel}><small>波次</small><strong>{hud.wave}/{hud.totalWaves}</strong></div><div className={styles.panel}><small>得分</small><strong>{hud.score.toLocaleString()}</strong></div><div className={styles.panel}><small>本次伤害</small><strong>{hud.damage}</strong></div><button className={styles.pause} onClick={()=>engineRef.current?.togglePause()}>{status==="paused"?"▶":"Ⅱ"}</button></div><div className={styles.health}><span><b>符文核心</b><b>{hud.hp}/{hud.maxHp}</b></span><div className={styles.bar}><i style={{width:`${hud.hp/hud.maxHp*100}%`}}/></div></div><div className={styles.coach}>{hud.message}</div><div className={styles.relics}>{hud.relics.map((icon,i)=><i key={`${icon}-${i}`}>{icon}</i>)}</div></>}
    {status==="idle"&&<div className={styles.overlay}><span className={styles.mark}>◉</span><h3>符文弹珠</h3><p>瞄准钉阵发射弹珠，点亮越多符文伤害越高。击败敌人后从三枚遗物中选择一枚，构筑属于你的弹珠核心。</p><ul><li>移动鼠标瞄准，点击 / 空格发射</li><li>黄色暴击 · 红色爆炸 · 绿色刷新</li><li>P 暂停</li></ul><button onClick={()=>engineRef.current?.start()}>进入星门</button></div>}
    {status==="upgrade"&&<><h3 className={styles.upgradeTitle}>选择一枚战利品</h3><div className={styles.choices}>{choices.map(choice=><button className={styles.choice} key={choice.id} onClick={()=>engineRef.current?.chooseUpgrade(choice.id)}><b>{choice.icon}</b><strong>{choice.name}</strong><span>{choice.description}</span></button>)}</div></>}
    {(status==="won"||status==="lost")&&<div className={styles.overlay}><span className={styles.mark}>{status==="won"?"✦":"◉"}</span><h3>{status==="won"?"星门净化完成":"符文核心破碎"}</h3><p>{result}。本局 {hud.score.toLocaleString()} 分，历史最高 {Math.max(bestScore,hud.score).toLocaleString()}。</p><ul><li>抵达第 {hud.wave} 波</li><li>完成 {hud.shot} 次发射</li></ul><button onClick={()=>engineRef.current?.start()}>重新构筑</button></div>}
  </div>;
}
